outdir: "output/"
tsv: './visium_template.tsv'

# Already processed files to generate config file
raw:
  zarr: "Test_visium_raw.zarr"
  md:
    channel_names: ["channel_1"]
label:
  zarr: "Test_visium_label.zarr"
  md: []
files:
  - "Test_visium_anndata.zarr"

title: "Test"
dataset: "visium"
url: "https://hindlimb.cog.sanger.ac.uk/datasets/visium/"
options:
  spatial:
    xy: "obsm/spatial"
  mappings:
    obsm/X_umap: [0,1]
    obsm/X_pca: [0,1]
  factors:
    - "obs/sample"
  sets:
    - "obs/sample"
  matrix: "X"
layout: 'advanced'
# custom_layout: "spatial|((scatterplot/scatterplot)|(genes/cellSets))"
